apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # stage server: https://acme-staging-v02.api.letsencrypt.org/directory
    # production server: https://acme-v02.api.letsencrypt.org/directory
    email: sandysandesh28@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-key
    solvers:
      - dns01:
          cloudflare:
            email: sandysandesh28@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
